Vagrant.configure('2') do |config|
  config.ssh.username = 'ubuntu'
  config.ssh.private_key_path = "../env/at12.pen"
  config.vm.provider :openstack do |os, override|
    os.identity_api_version = ENV['OS_IDENTITY_API_VERSION']
    os.openstack_auth_url = ENV['OS_AUTH_URL']
    os.domain_name = ENV['OS_DOMAIN_NAME']
    os.username = ENV['OS_USERNAME']
    os.password = ENV['OS_PASSWORD']
    os.project_name = ENV['OS_PROJECT_NAME']
    os.keypair_name = ENV['OS_KEY_PAIR_NAME']
    os.image = ENV['OS_IMAGE']
    os.flavor = ENV['OS_FLAVOR']
  end
  config.vm.define 'svr-PROG102' do |s|
    s.vm.provider :openstack do |os, override|
      os.server_name = 'AT12MR_PROG102_Jenkins'
      override.vm.synced_folder '.', '/vagrant', disabled: true
    end
    s.vm.provision "docker"
    s.vm.provision "docker_compose", compose_version: '1.25.4'
    s.vm.provision "file", source: "yml/docker-compose.yml", destination: "/tmp/"
    s.vm.provision "shell", path: "scripts/runDockerCompose.sh"
  end
end